[project]
name = "xeus-stata"
version = "0.1.0"
description = "A Jupyter kernel for Stata based on the xeus framework"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
xeus = ">=5.0"
xeus-zmq = ">=3.0"
xtl = ">=0.7"
nlohmann_json = ">=3.11"
cppzmq = "*"
cmake = ">=3.8"
ninja = "*"
cxx-compiler = "*"
gtest = "*"
jupyterlab = "*"
